name: IPFS Cluster Pipeline
on:
  push:
    branches:
      - main
      - master
    paths:
      - 'Dockerfile.ipfs-cluster'
jobs:
  push_to_registry:
    name: Build and publish IPFS Cluster
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3.1.0
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set the IPFS Cluster version
        id: ipfs_cluster_version
        run: echo IPFS_CLUSTER_VERSION=$(cat Dockerfile.ipfs-cluster | grep 'ARG IPFS_CLUSTER_VERSION' | cut -d'=' -f2) >> $GITHUB_ENV
      - name: Build and publish container image
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile.ipfs-cluster
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/ipfs-cluster:${{ github.sha }}
            ghcr.io/${{ github.repository }}/ipfs-cluster:${{ env.IPFS_CLUSTER_VERSION }}
