name: CoreDNS Pipeline
on:
  push:
    branches:
      - main
      - master
    paths:
      - 'Dockerfile.coredns'
jobs:
  push_to_registry:
    name: Build and publish CoreDNS
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set the CoreDNS version
        id: coredns_version
        run: echo COREDNS_VERSION=$(cat Dockerfile.coredns | grep 'ARG COREDNS_VERSION' | cut -d'=' -f2) >> $GITHUB_ENV
      - name: Build and publish container image
        uses: docker/build-push-action@v3
        with:
          file: ./Dockerfile.coredns
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/coredns:${{ github.sha }}
            ghcr.io/${{ github.repository }}/coredns:${{ env.COREDNS_VERSION }}