name: Go IPFS Pipeline
on:
  push:
    branches:
      - main
      - master
    paths:
      - 'Dockerfile.ipfs-go'
jobs:
  push_to_registry:
    name: Build and publish Go IPFS
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set the Go IPFS version
        id: ipfs_go_version
        run: echo IPFS_GO_VERSION=$(cat Dockerfile.ipfs-go | grep 'ARG IPFS_VERSION' | cut -d'=' -f2) >> $GITHUB_ENV
      - name: Build and publush container image
        uses: docker/build-push-action@v3
        with:
          file: ./Dockerfile.ipfs-go
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/ipfs-go:${{ github.sha }}
            ghcr.io/${{ github.repository }}/ipfs-go:${{ env.IPFS_GO_VERSION }}
