name: Caddy Pre-Flight Checks
on:
  pull_request:
    paths:
      - 'Dockerfile.caddy'
jobs:
  push_to_registry:
    name: Security analysis for Caddy image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3.0.2
      - name: Build image
        id: build_image
        run: docker build --rm -f Dockerfile.caddy -t caddy:${{ github.sha }} .
      - name: hadolint
        id: hadolint
        uses: hadolint/hadolint-action@v1.6.0
        with:
          dockerfile: ./Dockerfile.caddy
          failure-threshold: warning
          ignore: DL3026
      - name: Container scan
        id: container_scan
        uses: Azure/container-scan@v0
        with:
          image-name: caddy:${{ github.sha }}