name: CoreDNS Pre-Flight Checks
on:
  pull_request:
    paths:
      - 'Dockerfile.coredns'
jobs:
  push_to_registry:
    name: Security analysis for Coredns image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Build image
        id: build_image
        run: docker build --rm -f Dockerfile.coredns -t coredns:${{ github.sha }} .
      - name: hadolint
        id: hadolint
        uses: hadolint/hadolint-action@v1.5.0
        with:
          dockerfile: ./Dockerfile.coredns
          failure-threshold: warning
          ignore: DL3003 DL3008 DL3015 DL3026
      - name: Container scan
        id: container_scan
        uses: Azure/container-scan@v0
        with:
          image-name: coredns:${{ github.sha }}