name: Go Ethereum Pre-Flight Checks
on:
  pull_request:
    paths:
      - 'Dockerfile.go-ethereum'
jobs:
  push_to_registry:
    name: Security analysis for Go Ethereum image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Build image
        id: build_image
        run: docker build --rm -f Dockerfile.go-ethereum -t go-ethereum:${{ github.sha }} .
      - name: hadolint
        id: hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./Dockerfile.go-ethereum
          failure-threshold: warning
          ignore: DL3026
      - name: Container scan
        id: container_scan
        uses: Azure/container-scan@v0
        with:
          image-name: go-ethereum:${{ github.sha }}